[build]
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[functions."search"]
  timeout = 60

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
